/* 
 This file was generated by Dashcode and is covered by the 
 license.txt included in the project.  You may edit this file, 
 however it is recommended to first turn off the Dashcode 
 code generator otherwise the changes will be lost.
 */
var dashcodePartSpecs = {
    "bug-report": { "creationFunction": "CreateText", "text": "Found a bug? Please report it to us →" },
    "check_settings": { "creationFunction": "CreateButton", "leftImageWidth": 2, "onclick": "saveAndCheckLogin", "rightImageWidth": 2, "text": "check settings" },
    "done": { "creationFunction": "CreateGlassButton", "onclick": "saveAndshowFront", "text": "Done" },
    "info": { "backgroundStyle": "black", "creationFunction": "CreateInfoButton", "foregroundStyle": "white", "frontID": "front", "onclick": "showBack" },
    "Reload": { "creationFunction": "CreateGlassButton", "onclick": "reloadData", "text": "Reload" },
    "sign_up": { "creationFunction": "CreateButton", "leftImageWidth": 2, "onclick": "signup", "rightImageWidth": 2, "text": "sign up free" },
    "signup_lead_label": { "creationFunction": "CreateText", "text": "Don't have a Tiktrac account?" },
    "task-container": { "autoHideScrollbars": true, "creationFunction": "CreateScrollArea", "hasVerticalScrollbar": true, "rightMargin": 2, "scrollbarDivSize": 18, "scrollbarMargin": 6, "spacing": -1 },
    "text": { "creationFunction": "CreateText", "text": "Sheet" },
    "text1": { "creationFunction": "CreateText", "text": "Add a task" },
    "text2": { "creationFunction": "CreateText", "text": "Email" },
    "text3": { "creationFunction": "CreateText", "text": "Password" },
    "text4": { "creationFunction": "CreateText", "text": "Tiktrac URL" },
    "text5": { "creationFunction": "CreateText", "text": "Tiktrac" }
};
