// This file was generated by Dashcode from Apple Inc.
// You may edit this file to customize your Dashboard widget.

function clear_tasks_content()
{
    $$('#tasks.li').each(function(task) {
        task.remove()
    })
}

//
// Function: load()
// Called by HTML body element's onload event when the widget is ready to start
//
function load()
{
    setupParts()
	tiktrac = null
	
    login_credentials_valid(loadTiktrac, showBack)
    
    Feedback.clear()
}

//
// Function: remove()
// Called when the widget has been removed from the Dashboard
//
function remove()
{
	if (tiktrac && tiktrac.tasks.timer.running)
	{
		tiktrac.tasks.stopTimer()
	}

	widget.setPreferenceForKey(null, "userAccountName")
	widget.setPreferenceForKey(null, "userEmail");
	widget.setPreferenceForKey(null, "userPass");
    widget.setPreferenceForKey(null, "userSheet");
}

//
// Function: hide()
// Called when the widget has been hidden
//
function hide()
{
    // Stop any timers to prevent CPU usage
}

//
// Function: show()
// Called when the widget has been shown
//
function show()
{
    // Restart any timers that were stopped on hide
}

//
// Function: sync()
// Called when the widget has been synchronized with .Mac
//
function sync()
{
    // Retrieve any preference values that you need to be synchronized here
    // Use this for an instance key's value:
    // instancePreferenceValue = widget.preferenceForKey(null, createInstancePreferenceKey("your-key"));
    //
    // Or this for global key's value:
    // globalPreferenceValue = widget.preferenceForKey(null, "your-key");
}

//
// Function: showBack(event)
// Called when the info button is clicked to show the back of the widget
//
// event: onClick event from the info button
//
function showBack(event)
{
    var front = document.getElementById("front");
    var back = document.getElementById("back");

    if (window.widget) {
		$('accountname').value = (widget.preferenceForKey("userAccountName") != undefined) ? widget.preferenceForKey("userAccountName") : ''
		$('email').value = (widget.preferenceForKey("userEmail") != undefined) ? widget.preferenceForKey("userEmail") : ''
		$('password').value = (widget.preferenceForKey("userPass") != undefined) ? widget.preferenceForKey("userPass") : ''

        widget.prepareForTransition("ToBack");
    }

    front.style.display = "none";
    back.style.display = "block";

    if (window.widget) {
        setTimeout('widget.performTransition();', 0);
    }
    check_login()
}

function login_credentials_valid(callback_success, callback_failure)
{
	var accountName = widget.preferenceForKey("userAccountName")
	var email = widget.preferenceForKey("userEmail")
	var pass = widget.preferenceForKey("userPass")
	var api = new TiktracRequest(accountName, email, pass)
	
	var response_handler_valid = function(r)
	{
		TiktracProfile.login_valid = true
		if (callback_success) callback_success()
	}

	var response_handler_invalid = function()
	{
		TiktracProfile.login_valid = false
		if (callback_failure)
		{
			callback_failure()
		}
        else
        {
            Feedback.message(getLocalizedString('login invalid'))
        }
	}
	
	api.valid(response_handler_valid, response_handler_invalid)
}

function check_login(callback)
{
	$('login_feedback').innerHTML = ''
    
    if (callback) {
        login_credentials_valid(callback)
    } else {
        login_credentials_valid(function() { $('login_feedback').innerHTML = getLocalizedString('login correct') }, function() { $('login_feedback').innerHTML = getLocalizedString('login invalid') } )
    }
}

//
// Function: showFront(event)
// Called when the done button is clicked from the back of the widget
//
// event: onClick event from the done button
//
function showFront(event)
{
    var front = document.getElementById("front");
    var back = document.getElementById("back");

    if (window.widget) {
        widget.prepareForTransition("ToFront")
    }

    front.style.display="block";
    back.style.display="none";

    if (window.widget) {
        setTimeout('widget.performTransition();', 0);
    }

    Feedback.clear()

	if (prefsAreSet())
	{
		loadTiktrac()
	}
	else
	{
		showBack() // Needs to pop up a message about giving details and possibly check they're correct
	}
}

function prefsAreSet()
{
	var accountName = widget.preferenceForKey("userAccountName")
	var email = widget.preferenceForKey("userEmail")
	var pass = widget.preferenceForKey("userPass")

	if (accountName == undefined || email == undefined || pass == undefined)
	{
		return false
	}
	else
	{
		if (accountName.blank() || email.blank() || pass.blank())
		{
			return false
		}
		else
		{
			return true
		}
	}
}

function loadTiktrac()
{
    if (tiktrac) {
      tiktrac.refreshData()
    } else {
	  tiktrac = new Tiktrac
    }
}

if (window.widget) {
    widget.onremove = remove;
    widget.onhide = hide;
    widget.onshow = show;
    widget.onsync = sync;
}


function saveAndshowFront(event)
{
    TiktracProfile.saveFromBack()
    check_login(showFront)
}


function saveAndCheckLogin(event)
{
    TiktracProfile.saveFromBack()
    check_login()
}


function signup(event)
{
	widget.openURL('http://tiktrac.com/signup')
}


function reloadData(event)
{
    tiktrac.refreshData();
}
